name: Book

on:
  push:
    branches:
    - master
  pull_request:
    paths:
    - 'book/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      run: |
        mkdir -p $HOME/mdbook $HOME/mdbook-linkcheck
        curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.0/mdbook-v0.4.0-x86_64-unknown-linux-gnu.tar.gz | tar xz -C $HOME/mdbook
        echo "::add-path::${HOME}/mdbook/"
        curl -L https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v0.7.0/mdbook-linkcheck-v0.7.0-x86_64-unknown-linux-gnu.tar.gz | tar xz -C $HOME/mdbook-linkcheck
        echo "::add-path::${HOME}/mdbook-linkcheck/"
        cargo install mdbook-mermaid --version '^0.4' --debug
    - name: Build
      run: mdbook build
      working-directory: book
    - uses: actions/upload-artifact@v2
      with:
        name: book
        path: book/book/html

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: book
    - uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      with:
        repo-token: ${{ secrets.GH_PAT }}
        site-directory: .
        commit-message: Deploy to GitHub Pages
